spring:
  datasource:
    url: jdbc:mysql://localhost:3306/desafio3?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  api:
    security:
      token:
        secret: ${JWT_SECRET:my-secret}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_GMAIL}
    password: heep krnw ghzl qjtb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com